version: "3.7"
networks:
  petclinic:
    driver: bridge
services:
  app:
    image: testapp
    ports:
      - 9090:8080
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
    networks:
      - petclinic
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    networks:
      - petclinic
